### PR TITLE
Introduced Webpack and ReactJS into the project

### PR DESCRIPTION
**Pull request by pcaldredbann**
Hi all. Please can you review this stuff.

I've introduced [Webpack](https://webpack.js.org/) and [ReactJS](https://reactjs.org/) into the project. Webpack is a tool we'll use for transpiling our ECMA2015 code into all-browser-friendly JavaScript, and eventually it'll build all our styling. Have a look at webpack.config.js for all the good details about what it's doing.

ReactJS is obviously our chosen framework for turning our code into a usable app. There's a lot to learn about it, but the basics are all here in how you create a React app, bind it to a DOM element in a file and serve that all up via a bundled (thanks to Webpack) script to a .html file for the user.

Have a go at checking this stuff out and see if you can get it working, simply do `git checkout dev-paul` then from a command line (or integrated terminal) type `npm install` to get all the dependencies, `npm run build` to build it all, and if you get to here `npm run start:debug` should give you a locally hosted version at http://localhost:8080 (if :8080 is in use already on your machine, feel free to change the port in webpack.config.js).

### CODE REVIEW

**Comment by CarlJTildsley** [comment]
Just one note on the checking out this branch. I did `git checkout dev-paul` and this actually created a local branch (didn't actually pull the branch). 

I did `git checkout origin/dev-paul` which worked :)

**Comment by pcaldredbann** [comment]
@CarlJTildsley that's odd... the only explanation I can think of for that is you must've had a local copy of `dev-paul` (as without the -b switch it throws an error). This would've been out of sync with remote (the origin/dev-paul one) so you would probably have been fine with doing `git pull` to get the latest branch changes.

**Comment by CarlJTildsley** [comment]
Either way I managed to get the app up and running in my browser :)

**Comment by pcaldredbann** [comment]
Just made a change to this PR via implementing (ESLint)[https://eslint.org/] which *should* help us to guarantee some kind of consistent code quality. Rules will be defined better as time goes on and more and more people contribute.

**Comment by pcaldredbann** [comment]
Merging this into `dev` before the PR gets too noisy with multiple commits.

**Pull request merged**
