### PR TITLE
Dev carl

### PR DESCRIPTION
**Pull request by CarlJTildsley**
Please can you review my pull request

### CODE REVIEW

**Comment by pcaldredbann** [comment]
Looks good to me! Why the `node_modules/` forward slash in `.gitignore`?

**Comment by moo369** [comment]
Aye

**Comment by CarlJTildsley** [comment]
/ removed - It was just so I can see which are file and which are folders :)

**Comment by pcaldredbann** [comment]
Ah I wasn't suggesting it was wrong... :) merely curious!

**Comment by pcaldredbann** [comment]
Re-opened PR as @moo369 "helpfully" closed it, thanks a lot!!! :)

**Comment by pcaldredbann** [comment]
@salmanmulla1 @JangirRiaz @moo369 still waiting for your approval / rejection - can you have a quick gander at files changed, click the drop-down on there called "Review Changes" and either approve or request changes / improvements.

**Comment by pcaldredbann** [comment]
There's a restriction on the *dev* branch at the moment - it requires 5 approvals before it can be merged into dev, just FYI

**Comment by moo369** [comment]
Pro Tip: Once you start typing a comment, the "Close Pull Request" button gets renamed to "Close and Comment", which is a bit ambiguous if you're an idiot. I learned this the hard way...

**Comment by pcaldredbann** [comment]
Haha @moo369 yes I've just noticed that... pretty stupid UI decision there, let's hope Micro$haft can do better!

**Comment by pcaldredbann** [comment]
Just @salmanmulla1 and @JangirRiaz dragging their feet now... :) I know it seems like such a little thing, but getting into the habit of doing PRs is a very good thing to do!

**Comment by pcaldredbann** [comment]
Closing as this PR has become stale now

**Pull request closed without merging**
